name: Build Godot Google Login AAR

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build AAR
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Set up Gradle
        uses: gradle/gradle-build-action@v3

      - name: Install Android SDK
        uses: android-actions/setup-android@v3
        with:
          api-levels: 34
          build-tools: 34.0.0
          cmake: false

      - name: Accept licenses
        run: yes | sdkmanager --licenses || true

      - name: Build AAR
        working-directory: GodotGoogleLogin
        run: |
          gradle assembleRelease

      - name: Upload built AAR
        uses: actions/upload-artifact@v4
        with:
          name: GodotGoogleLogin-AAR
          path: GodotGoogleLogin/build/outputs/aar/*.aar